<?php 

$listExample = [
    [
        /** Module Name 
         * use PascalCase to define module name, letter char tobe replacing with uderscore if you use 2 words like "UserSession = user_session"
        */
        "name" => "Users", // use PascalCase to define module name, letter tobe replacing with uderscore if you use 2 words li
        "loging_date" => true, // to activate created_at & updated_at including soft delete of table.
        "column" => [
            [
                "type" => "enum",  "name" => "id", 
                "length" => 18, 
                "length2" => 3, 
                "default" => "0", 
                "attributes" => ['index','nullable'], 
                "fulltext" => true,
                "enum_list" => "['open', 'closed', 'expired']"
            ],
        ],
    ]
];

$list = [
    /** DEFAULT MODULE
     * Be careful about changing / deleting the user & userSessions module, 
     * because this module is the default module for setting up authentication, 
     * unless you already understand or don't need it and are aware of the risks.
     * Users         : module to manage data user of application
     * UserSession     : module to manage all session of user logged in
    */ 
 
    ["name" => "Users",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "name",
                "type" => "string", 
            ],
            [ "name" => "username",
                "type" => "string", 
            ],
            [ "name" => "password",
                "type" => "string", 
            ],
            [ "name" => "email",
                "type" => "string", 
            ],
            [ "name" => "picture",
                "type" => "text", 
                "attributes" => ['nullable'], 
            ],
            [ "name" => "role_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "menu_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "department_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "active",
                "type" => "tinyInteger", 
                "default" => 0, 
            ],
            
        ],
    ],

    ["name" => "UserSessions",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "user_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['index'],
            ],
            [ "name" => "token",
                "type" => "text", 
            ],
            [ "name" => "ip",
                "type" => "string", 
                "attributes" => ['nullable'], 
            ],
            [ "name" => "agent",
                "type" => "string", 
                "attributes" => ['nullable'], 
            ],
            [ "name" => "platform",
                "type" => "string", 
                "attributes" => ['nullable'], 
            ],
            
        ],
    ],

    ["name" => "Permissions",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string", 
            ],
            [ "name" => "slug",
                "type" => "string", 
                "attributes" => ['nullable'], 
            ],
            
        ],
    ],

    ["name" => "RolePermissions",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "permission_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['index'],
            ],
            [ "name" => "role_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['index'],
            ],
            
        ],
    ],

    ["name" => "Roles",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string", 
            ],
            [ "name" => "slug",
                "type" => "string", 
                "attributes" => ['nullable'], 
            ],
            
        ],
    ],

    ["name" => "MenuItems",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string",
            ],
            [ "name" => "slug",
                "type" => "string",
                "attributes" => ['index'],
            ],
            [ "name" => "icon",
                "type" => "text",
                "attributes" => ['nullable'],
            ],
            [ "name" => "path",
                "type" => "text",
                "attributes" => ['nullable'],
            ],
            
        ],
    ],

    ["name" => "Menus",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "parent_id",
                "type" => "unsignedBigInteger", 
                "attributes" => ['index', 'nullable'],
            ],
            [ "name" => "menu_item_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['index'],
            ],
            [ "name" => "master_menu_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['index'],
            ],
            [ "name" => "overline",
                "type" => "string",
                "attributes" => ['nullable'],
            ],
            [ "name" => "ordering",
                "type" => "integer", 
                "default" => "0",
            ],
            
        ],
    ],

    ["name" => "MasterMenus",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string",
            ],
            
        ],
    ],

    ["name" => "UserNotifications",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "user_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['index'],
            ],
            [ "name" => "is_read",
                "type" => "boolean",
                "default" => "false",
            ],
            [ "name" => "title",
                "type" => "string", 
                "attributes" => ['nullable'],
                "fulltext" => true, 
            ],
            [ "name" => "description",
                "type" => "text", 
                "attributes" => ['nullable'],
                "fulltext" => true, 
            ],
            [ "name" => "type",
                "type" => "string", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "link_path",
                "type" => "string", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "link_params",
                "type" => "json", 
                "attributes" => ['nullable'],
            ],
            
        ],
    ],

    ["name" => "Countries",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "code",
                "type" => "string",
            ],
            [ "name" => "name",
                "type" => "string",
            ],
            [ "name" => "official_state_name",
                "type" => "string",
            ]
        ],
    ],

    ["name" => "Provinces",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "country_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string",
            ]
        ],
    ],

    ["name" => "Cities",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "province_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string",
            ]
        ],
    ],

    ["name" => "ClassSocieties",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "code",
                "type" => "string",
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string",
            ]
        ],
    ],

    ["name" => "Departments",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "parent_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'],
            ],
            [ "name" => "code",
                "type" => "string",
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string",
            ]
        ],
    ],

    ["name" => "ParameterGroups",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "code",
                "type" => "string",
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string",
            ]
        ],
    ],

    ["name" => "Parameters",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "parameter_group_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'],
            ],
            [ "name" => "code",
                "type" => "string",
                "attributes" => ['index'],
            ],
            [ "name" => "description",
                "type" => "string",
            ],
            [ "name" => "type",
                "type" => "enum",
                "default" => "'string'",
                "enum_list" => "['string', 'boolean', 'integer', 'float', 'json']"
            ],
            [ "name" => "value",
                "type" => "longtext",
            ],
            [ "name" => "system_parameter",
                "type" => "tinyInteger",
                "default" => "0",
            ]
        ],
    ],

    ["name" => "Customers",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "code",
                "type" => "string",
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string",
            ],
            [ "name" => "telephone",
                "type" => "string",
                "attributes" => ['nullable'],
            ],
            [ "name" => "fax",
                "type" => "string",
                "attributes" => ['nullable'],
            ],
            [ "name" => "email",
                "type" => "string",
                "attributes" => ['nullable'],
            ],
            // address
            [ "name" => "address_street",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "address_country",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "address_province",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "address_city",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "address_zip_code",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            // contact person
            [ "name" => "contact_name",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "contact_mobile",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "contact_email",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            // tax info
            [ "name" => "tax_number",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "tax_street",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "tax_country",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "tax_province",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "tax_city",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "tax_zip_code",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            // billing info
            [ "name" => "billing_name",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "billing_telephone",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "billing_street",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "billing_country",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "billing_province",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "billing_city",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "billing_zip_code",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            // shipping info
            [ "name" => "shipping_name",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "shipping_telephone",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "shipping_street",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "shipping_country",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "shipping_province",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "shipping_city",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "shipping_zip_code",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
        ],
    ],

    ["name" => "QuestionnaireGroups",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "code",
                "type" => "string",
            ],
            [ "name" => "name",
                "type" => "string",
            ],
        ],
    ],

    ["name" => "Questionnaires",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "name",
                "type" => "string",
            ],
            [ "name" => "description",
                "type" => "text",
            ],
            [ "name" => "questionnaire_group_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
        ],
    ],

    ["name" => "QuestionnaireSections",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "label",
                "type" => "string",
            ],
            [ "name" => "questionnaire_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
        ],
    ],

    ["name" => "QuestionnaireDetails",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "label",
                "type" => "string",
            ],
            [ "name" => "type",
                "type" => "enum",
                "enum_list" => "['dropdown', 'paragraph', 'text', 'number', 'checklist', 'option', 'date', 'time', 'datetime', 'rating']"
            ],
            [ "name" => "questionnaire_section_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "value_ref", // khusus untuk : dropdown, checklist, option
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "key", // where selector nya  | khusus untuk : dropdown, checklist, option
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "value", // value selector | khusus untuk : dropdown, checklist, option
                "type" => "json",
                "attributes" => ["nullable"],
            ],
            [ "name" => "option_label",
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "option_value",
                "type" => "string",
                "attributes" => ["nullable"],
            ],
        ],
    ],

    ["name" => "Prospects",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "questionnaire_id", // questionnaire
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "document_number",
                "type" => "string",
            ],
            [ "name" => "document_date",
                "type" => "dateTime",
            ],
            [ "name" => "customer_id", // customer
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "end_customer_id", // customer
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "name",
                "type" => "string",
            ],
            [ "name" => "parameter_phase", // source : parameters : 100001
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "parameter_type", // source : parameters : 100002
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "parameter_vessel_type", // source : parameters : 100003
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "parameter_rfq_purpose", // source : parameters : 100004
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "parameter_sector", // source : parameters : 100005
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "qty",
                "type" => "double",
                "length" => 18, 
                "length2" => 2, 
            ],
            [ "name" => "status",
                "type" => "enum",
                "default" => "'FORECAST'",
                "enum_list" => "['FORECAST', 'POTENTIAL', 'HOT PROSPECT']"
            ],
            // class di list perlu ditanya om iki
        ],
    ],
    
    ["name" => "ProspectSections",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "label",
                "type" => "string",
            ],
            [ "name" => "prospect_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
        ],
    ],

    ["name" => "ProspectDetails",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "questionnaire_detail_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "label",
                "type" => "string",
            ],
            [ "name" => "type",
                "type" => "enum",
                "enum_list" => "['dropdown', 'paragraph', 'text', 'number', 'checklist', 'option', 'date', 'time', 'datetime', 'rating']"
            ],
            [ "name" => "prospect_section_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "value_ref", // khusus untuk : dropdown, checklist, option
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "key", // where selector nya  | khusus untuk : dropdown, checklist, option
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "value", // value selector | khusus untuk : dropdown, checklist, option
                "type" => "json",
                "attributes" => ["nullable"],
            ],
            [ "name" => "option_label",
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "option_value",
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "answer", // nilai yg di input user
                "type" => "text",
                "attributes" => ["nullable"],
            ],
        ],
    ],

    ["name" => "Activities",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "reference", // Model Name
                "type" => "string",
                "attributes" => ["index"],
            ],
            [ "name" => "reference_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "title",
                "type" => "string",
            ],
            [ "name" => "description",
                "type" => "text",
                "attributes" => ["nullable"],
            ],
            [ "name" => "due", // dipake untuk prospect, untuk menentukan waktu tenggang
                "type" => "dateTime",
                "attributes" => ["nullable"],
            ],
        ],
    ],

    ["name" => "ActivityFiles",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "activity_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "name",
                "type" => "string",
            ],
            [ "name" => "size",
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "type",
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "path", // /localtion/path/
                "type" => "string",
                "attributes" => ["nullable"],
            ],
        ],
    ],

    // need generate

    ["name" => "ProspectPhaseMapping",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "prospect_phase", // list nya ambil dari Parameters : 100001
                "type" => "unsignedBigInteger",
            ],
            [ "name" => "step", // isinya id department, pilihan nya list department
                "type" => "integer",
            ],
            [ "name" => "user_department", // isinya id department, pilihan nya list department
                "type" => "json",
            ],
        ],
    ],

    ["name" => "VendorGroups",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "code",
                "type" => "string",
            ],
            [ "name" => "name",
                "type" => "string",
            ],
            [ "name" => "description",
                "type" => "text",
                "attributes" => ['nullable'], 
            ],
        ],
    ],

    ["name" => "Vendors",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "vendor_group_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "code",
                "type" => "string",
                "attributes" => ['index'],
            ],
            [ "name" => "name",
                "type" => "string",
            ],
            [ "name" => "telephone",
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "fax",
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "email",
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            // [ "name" => "status",
            //     "type" => "enum",
            //     "default" => "'POTENTIAL'",
            //     "enum_list" => "['POTENTIAL', 'FORECAST']"
            // ],
            // address
            [ "name" => "address_street",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "address_country",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "address_province",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "address_city",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "address_zip_code",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
             // tax info
             [ "name" => "tax_number",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "tax_street",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "tax_country",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "tax_province",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "tax_city",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "tax_zip_code",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            // contact person
            [ "name" => "contact_name",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "contact_mobile",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "contact_email",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "detail",
                "type" => "text",
                "attributes" => ['nullable'], 
            ],
            // product info
            [ "name" => "group",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "brand",
                "type" => "string",
                "attributes" => ['nullable'], 
            ],

            [ "name" => "remarks",
                "type" => "text",
                "attributes" => ['nullable'], 
            ],

            [ "name" => "status",
                "type"      => "enum",
                "default"   => "'new'",
                "enum_list" => "['new','response','under review','document completed','document incompleted','rejected','approved']",
            ],

            [ "name" => "user_id",
                "type" => "unsignedBigInteger",
                "attributes" => ['nullable'], 
            ],
        ],
    ],

    ["name" => "Quotations",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "code", // autogenerate dengan format : MKT/KS/QO/040/II/{YYYY}
                "type" => "string",
            ],
            [ "name" => "customer_id", // customer
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "date",
                "type" => "dateTime",
            ],
            [ "name" => "agreement_number",
                "type" => "string",
            ],
            [ "name" => "subject",
                "type" => "string",
            ],
            [ "name" => "parameter_status", // source : parameters : 200001
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "remarks",
                "type" => "text",
                "attributes" => ["nullable"],
            ],
            [ "name" => "subtotal",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "discount",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "tax",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "total",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "requested_by", // #1
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "approved_by", // #2
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "rejected_by", // #2
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],

            [ "name" => "note",
                "type" => "text",
                "attributes" => ["nullable"],
            ],
        ],
    ],

    ["name" => "QuotationItems",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "quotation_id", // Quotations
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "description",
                "type" => "text",
            ],
            [ "name" => "parameter_unit", // source : parameters : 200001
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "quantity",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "price",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "amount",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],

        ],
    ],

    ["name" => "ConfirmPurchaseOrders",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "quotation_id",
                "type" => "unsignedBigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "prospect_id",
                "type" => "unsignedBigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "code", // autogenerate dengan format : MKT/KS/QO/040/II/{YYYY}
                "type" => "string",
            ],
            [ "name" => "customer_id", // customer
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "date",
                "type" => "dateTime",
            ],
            [ "name" => "agreement_number",
                "type" => "string",
            ],
            [ "name" => "subject",
                "type" => "string",
            ],
            [ "name" => "parameter_status", // source : parameters : 200001
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "remarks",
                "type" => "text",
                "attributes" => ["nullable"],
            ],
            [ "name" => "subtotal",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "discount",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "tax",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "total",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "status_payment",
                "type" => "string",
            ],
            [ "name" => "requested_by", // #1
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "approved_by", // #2
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "rejected_by", // #2
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "approved_director_first_by", // #2
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "rejected_director_first_by", // #2
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "approved_director_second_by", // #
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "rejected_director_second_by", // #
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],

            [ "name" => "note",
                "type" => "text",
                "attributes" => ["nullable"],
            ],
        ],
    ],

    ["name" => "ConfirmPurchaseOrderItems",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "confirm_purchase_order_id", // Quotations
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "description",
                "type" => "text",
            ],
            [ "name" => "parameter_unit", // source : parameters : 200001
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "quantity",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "price",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "amount",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],

        ],
    ],

    ["name" => "Warehouses",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "code",
                "type" => "string",
            ],
            [ "name" => "name",
                "type" => "string",
            ],
            [ "name" => "street_address",
                "type" => "text",
                "attributes" => ["nullable"],
            ],
            [ "name" => "country_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "province_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "city_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "zip_code",
                "type" => "string",
                "length" => 10
            ],
            [ "name" => "pic",
                "type" => "string",
            ],
            [ "name" => "mobile",
                "type" => "string",
                "length" => 20,
            ],
            [ "name" => "telephone",
                "type" => "string",
                "length" => 20,
            ],
            [ "name" => "email",
                "type" => "string",
                "length" => 100,
            ],
            [ "name" => "remarks",
                "type" => "text",
                "attributes" => ["nullable"],
            ],
        ],
    ],

    ["name" => "Items",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "code",
                "type" => "string",
            ],
            [ "name" => "type",
                "type"      => "enum",
                "default"   => "'material'",
                "enum_list" => "['inventory', 'non inventory']",
            ],
            [ "name" => "name",
                "type" => "string",
            ],
            [ "name" => "min_stock",
                "type"       => "double",
                "length"     => 18,
                "length2"    => 2,
                "attributes" => ["nullable"],
            ],
            [ "name" => "max_stock",
                "type"       => "double",
                "length"     => 18,
                "length2"    => 2,
                "attributes" => ["nullable"],
            ],
            [ "name" => "weight",
                "type"       => "double",
                "length"     => 18,
                "length2"    => 2,
                "attributes" => ["nullable"],
            ],
            [ "name" => "price",
                "type"       => "double",
                "length"     => 18,
                "length2"    => 2,
                "attributes" => ["nullable"],
            ],
            [ "name" => "item_unit_id", // ItemMeta:unit
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "item_group_id", // ItemMeta:group
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "item_category_id", // ItemMeta:category
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "item_uom_id", // ItemMeta:Uom
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "is_procured",
                "type" => "boolean",
                "default" => "false",
            ],
            [ "name" => "is_manufactured",
                "type" => "boolean",
                "default" => "false",
            ],
            [ "name" => "is_quality_control",
                "type" => "boolean",
                "default" => "false",
            ],
            [ "name" => "remarks",
                "type" => "longtext",
                "attributes" => ['nullable']
            ],
        ],
    ],

    ["name" => "ItemMeta",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "name",
                "type" => "string",
            ],
            [ "name" => "type",
                "type" => "enum",
                "default" => "'unit'",
                "enum_list" => "['group', 'category', 'uom', 'unit']"
            ],
        ],
    ],
    ["name" => "ConfirmPurchaseOrderPayments",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "confirm_purchase_order_id",
                "type" => "unsignedBigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "code",
                "type" => "string",
            ],
            [ "name" => "payment_date",
                "type" => "dateTime",
            ],
            [ "name" => "previous_payment",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
                "attributes" => ["nullable"],
            ],
            [ "name" => "payment_amount",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "outstanding",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
                "attributes" => ["nullable"],
            ],
        ],
    ],

    ["name" => "SalesOrders",
        "column" => [
            [ "name" => "code",
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "customer_id", // customer
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "date",
                "type" => "dateTime",
            ],
            [ "name" => "parameter_fob", // source : parameters : 200001
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "parameter_status", // source : parameters : 200001
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "remarks",
                "type" => "text",
                "attributes" => ["nullable"],
            ],
            [ "name" => "subtotal",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
            [ "name" => "discount",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
            [ "name" => "tax",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
            [ "name" => "total",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
            [ "name" => "requested_by", // #1
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "approved_by", // #2
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "rejected_by", // #2
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],

            [ "name" => "note",
                "type" => "text",
                "attributes" => ["nullable"],
            ],
        ],
    ],

    ["name" => "SalesOrderItems",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "sales_order_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "item_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "quantity",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
            [ "name" => "price",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
            [ "name" => "amount",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
        ],
    ],

    ["name" => "SalesOrderInvoices",
        "column" => [
            [ "name" => "code",
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "sales_order_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "good_issue_id", // must by approved and DO already generated
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "invoice_date",
                "type" => "date",
            ],
            [ "name" => "remarks",
                "type" => "text",
                "attributes" => ["nullable"],
            ],
            [ "name" => "subtotal",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
            [ "name" => "discount",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
            [ "name" => "total",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
        ],
    ],

    ["name" => "SalesOrderInvoiceItems",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "sales_order_invoice_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "sales_order_item_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "item_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "qty",
                "type" => "double",
                "length" => 18,
                "length2" => 2,
            ],
            [ "name" => "price",
                "type" => "double",
                "length" => 18,
                "length2" => 2,
            ],
            [ "name" => "discount",
                "type" => "double",
                "length" => 18,
                "length2" => 2,
                "attributes" => ["nullable"],
            ],
            [ "name" => "amount",
                "type" => "double",
                "length" => 18,
                "length2" => 2,
            ],
        ],
    ],

    ["name" => "SalesOrderPayments",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "code",
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "sales_order_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "sales_order_invoice_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "amount",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
            [ "name" => "payment_date",
                "type"   => "datetime",
                "length" => null,
            ],
            [ "name" => "remarks",
                "type" => "text",
                "attributes" => ["nullable"],
            ],
        ],
    ],

    ["name" => "ItemWarehouses",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "warehouse_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "item_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "stock",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
        ],
    ],

    ["name" => "ConfirmPurchaseOrderPaymentPlans",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "confirm_purchase_order_payment_id", // CPO Payments
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "percent",
                "type"      => "double",
                "length"      => 5,
                "length2"      => 2,
            ],
            [ "name" => "amount_plan",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "date_plan",
                "type" => "date",
            ],
            [ "name" => "payment_paid",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "payment_date",
                "type" => "dateTime",
                "attributes" => ["nullable"],
            ],
        ],
    ],

    ["name" => "Opnames",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "opname_date",
                "type" => "date",
                "attributes" => ["index"],
            ],
            [ "name" => "warehouse_id",
                "type" => "date",
                "attributes" => ["index"],
            ],
        ],
    ],

    ["name" => "OpnameDetails",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "opname_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "item_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "current_stock",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
            [ "name" => "latest_stock",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
        ],
    ],

    ["name" => "ItemLogs",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "ref",
                "type" => "enum",
                "enum_list" => "['op', 'so', 'gi', 'gr']"
            ],
            [ "name" => "ref_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "item_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "warehouse_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "debit",
                "type"       => "double",
                "length"     => 18,
                "length2"    => 2,
                "attributes" => ["nullable"],
            ],
            [ "name" => "credit",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
                "attributes" => ["nullable"],
            ],
            [ "name" => "balance",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
        ],
    ],

    ["name" => "ItemGroups",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "parent_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "name",
                "type" => "string",
            ],
        ],
    ],

    ["name" => "GoodIssues",
        "loging_date" => true,
        "loging_user" => true,
        "column" => [
            [ "name" => "id",
                "type" => "bigIncrements",
                "attributes" => ["index"],
            ],
            [ "name" => "sales_order_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "requested_by",
                "type" => "unsignedBigInteger",
                "attributes" => ["index", "nullable"],
            ],
            [ "name" => "approved_by",
                "type" => "unsignedBigInteger",
                "attributes" => ["index", "nullable"],
            ],
            [ "name" => "rejected_by",
                "type" => "unsignedBigInteger",
                "attributes" => ["index", "nullable"],
            ],
        ],
    ],

    ["name" => "GoodIssueItems",
        "loging_date" => true,
        "loging_user" => true,
        "column" => [
            [ "name" => "id",
                "type" => "bigIncrements",
                "attributes" => ["index"],
            ],
            [ "name" => "delevery_order_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "sales_order_item_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index", "nullable"],
            ],
            [ "name" => "item_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index", "nullable"],
            ],
            [ "name" => "qty",
                "type" => "double",
                "length"  => 18,
                "length2" => 2,
            ],
            [ "name" => "price",
                "type" => "double",
                "length"  => 18,
                "length2" => 2,
            ],
        ],
    ],

    ["name" => "MasterCurrencies",
        "loging_date" => true,
        "loging_user" => true,
        "column" => [
            [ "name" => "id",
                "type" => "bigIncrements",
                "attributes" => ["index"],
            ],
            [ "name" => "code",
                "type" => "string", 
            ],
            [ "name" => "name",
                "type" => "string", 
            ],
            [ "name" => "base_currency",
                "type" => "boolean",
                "default" => "false",
            ]
        ],
    ],

    ["name" => "ExchangeRates",
        "loging_date" => true,
        "loging_user" => true,
        "column" => [
            [ "name" => "id",
                "type" => "bigIncrements",
                "attributes" => ["index"],
            ],
            [ "name" => "currency_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "datetime",
                "type" => "dateTime", 
            ],
            [ "name" => "amount",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ]
        ],
    ],

    ["name" => "LegalFiles",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "reference", // Model Name
                "type" => "string",
                "attributes" => ["index"],
            ],
            [ "name" => "reference_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "description",
                "type" => "text",
                "attributes" => ["nullable"],
            ],
            [ "name" => "name",
                "type" => "string",
            ],
            [ "name" => "size",
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "type",
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "path", // /localtion/path/
                "type" => "string",
                "attributes" => ["nullable"],
            ],
        ],
    ],

    ["name" => "VendorItems",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "item_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "vendor_id",
                "type" => "text",
                "attributes" => ["nullable"],
            ],
            [ "name" => "code",
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "name",
                "type" => "string",
                "attributes" => ["nullable"],
            ],
            [ "name" => "description",
                "type" => "text", 
                "attributes" => ['nullable'],
                "fulltext" => true, 
            ],
            [ "name" => "unit_id", // item_meta unit_id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "price",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
        ],
    ],

    ["name" => "PurchaseRequisition",
        "loging_date" => true,
        "loging_user" => true,
        "column" =>
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "code",
                "type" => "string", 
            ],
            [ "name" => "date",
                "type" => "dateTime", 
            ],
            [ "name" => "remarks",
                "type" => "text", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "department_id", // Item Departement
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "warehouse_id", // Item Warehouses
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "prepare_by", // Users
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "approved_by", // Users
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "received_by", // Users
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
        ],
    ],

    ["name" => "PurchaseRequisitionDetail",
        "loging_date" => true,
        "loging_user" => true,
        "column" =>
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'],
            ],
            [ "name" => "purchase_requisition_id", // Purchase Requisition
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "item_id", // Items
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "department_id", // Item Departement
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "project_id", // Item Project
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
                "attributes2" => ['nullable'],
            ],
            [ "name" => "qty",
                "type" => "double", 
                "length" => 18,
                "length2" => 2,
            ],
            [ "name" => "unit_id", // Item Meta
                "type" => "unsignedBigInteger", 
                "attributes" => ['index'],
            ],
            [ "name" => "required_date",
                "type" => "date", 
            ],
            [ "name" => "due_date_biding",
                "type" => "date",
                "attributes" => ['nullable'], 
            ],
            [ "name" => "biding_id",
            "type" => "unsignedBigInteger",
            "attributes" => ['index'], 
        ],
        ],
    ],

    ["name" => "PurchaseRequisitionVendor",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "vendor_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "purchase_requisition_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "purchase_requisition_detail_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "delivery_time",
                "type" => "date",
            ],
            [ "name" => "payment_term",
                "type" => "integer",
            ],
            [ "name" => "delivery_point",
                "type" => "string", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "currency_id", // master_currency
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            
            [ "name" => "item_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "price",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "rate",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "amount",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
        ],
    ],

    ["name" => "PurchaseWorkOrder",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "purchase_requisition_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index", "nullable"],
            ],
            [ "name" => "type", // value id
                "type" => "enum",
                "enum_list" => "['wo', 'po']",
            ],
            [ "name" => "vendor_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "currency_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "warehouse_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index", "nullable"],
            ],
            [ "name" => "rate",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "departement_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "code",
                "type" => "string",
            ],
            [ "name" => "date",
                "type" => "dateTime",
            ],
            [ "name" => "remarks",
                "type" => "string", 
                "attributes" => ['nullable'],
            ],
            [ "name" => "discount",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "discount_type", // value id
                "type" => "enum",
                "enum_list" => "['%', 'amount']",
            ],
            [ "name" => "subtotal",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "tax",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "estimated_freight",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "delivery_time",
                "type"      => "dateTime"
            ],
            [ "name" => "payment_term",
                "type"      => "integer"
            ],
            [ "name" => "delivery_point",
                "type"      => "string",
                "attributes" => ['nullable']
            ],
            [ "name" => "is_completed",
                "type" => "tinyInteger", 
                "default" => 0, 
            ],
            [ "name" => "is_paid",
                "type" => "tinyInteger", 
                "default" => 0, 
            ],
            [ "name" => "prepared_by", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "prepared_by", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ]
        ],
    ],

    ["name" => "PurchaseWorkOrderDetail",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "purchase_work_order_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "purchase_requisition_detail_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "item_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "project_id", // value id
                "type" => "unsignedBigInteger",
                "attributes" => ["index", "nullable"],
            ],
            [ "name" => "qty",
                "type"      => "integer",
            ],
            [ "name" => "payment_term",
                "type"      => "integer",
            ],
            [ "name" => "price",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "discount",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "discount_type", // value id
                "type" => "enum",
                "enum_list" => "['%', 'amount']",
            ],
            [ "name" => "amount",
                "type"      => "double",
                "length"      => 18,
                "length2"      => 2,
            ],
            [ "name" => "remarks",
                "type"      => "string",
                "attributes" => ['nullable']
            ],
        ],
    ],

    ["name" => "GoodsWorkReceive",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "type",
                "type" => "enum",
                "default" => "'po'",
                "enum_list" => "['po', 'wo']"
            ],
            [ "name" => "code",
                "type"      => "string",
                "attributes" => ['nullable']
            ],
            [ "name" => "department_id", // Item Deparment
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "reference_invoice",
                "type"      => "string",
                "attributes" => ['nullable']
            ],
            [ "name" => "purchase_work_order_id", // PurchaseWorkOrder
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "purchase_requisition_id", // PurchaseRequisition
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "remarks",
                "type"      => "text",
                "attributes" => ['nullable']
            ],
        ],
    ],

    ["name" => "GoodsWorkReceiveDetail",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "goods_work_receive_id", // GoodsWorkReceive
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "purchase_work_order_detail_id", // PurchaseWorkOrderDetail
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "purchase_requisition_detail_id", // PurchaseRequisition
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "qty",
                "type" => "double",
                "length" => 18, 
                "length2" => 2, 
            ],
        ],
    ],

    ["name" => "VendorCurrencies",
        "loging_date" => true,
        "loging_user" => true,
        "column" => 
        [
            [ "name" => "id",
                "type" => "bigIncrements", 
                "attributes" => ['index'], 
            ],
            [ "name" => "vendor_id", // Vendor
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "currency_id", // Master Currencies
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "balance",
                "type" => "double",
                "length" => 18, 
                "length2" => 2, 
            ],
        ],
    ],

    ["name" => "GlobalSettings",
        "loging_date" => true,
        "loging_user" => true,
        "column" => [
            [ "name" => "id",
                "type" => "bigIncrements",
                "attributes" => ['index'],
            ],
            [ "name" => "slug",
                "type" => "string",
                "length" => 50,
            ],
            [ "name" => "value",
                "type" => "text",
            ],
        ],
    ],

    ["name" => "GoodMovements",
        "loging_date" => true,
        "loging_user" => true,
        "column" => [
            [ "name" => "id",
                "type" => "bigIncrements",
                "attributes" => ['index'],
            ],
            [ "name" => "code",
                "type" => "string",
                "length" => 50,
            ],
            [ "name" => "good_movement_date",
                "type" => "date",
            ],
            [ "name" => "from_warehouse_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "to_warehouse_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "remarks",
                "type" => "text",
                "attributes" => ["nullable"],
            ],
            [ "name" => "delivery_order_code",
                "type" => "string",
                "length" => 50,
                "attributes" => ["nullable"],
            ],
            [ "name" => "delivery_order_date",
                "type" => "date",
                "attributes" => ["nullable"],
            ],
            [ "name" => "shipper_name",
                "type" => "string",
                "length" => 100,
                "attributes" => ["nullable"],
            ],
            [ "name" => "shipper_plate_number",
                "type" => "string",
                "length" => 50,
                "attributes" => ["nullable"],
            ],
            [ "name" => "requested_by",
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "approved_by",
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "rejected_by",
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
        ],
    ],

    ["name" => "GoodMovementItems",
        "loging_date" => true,
        "loging_user" => true,
        "column" => [
            [ "name" => "id",
                "type" => "bigIncrements",
                "attributes" => ['index'],
            ],
            [ "name" => "good_movement_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "item_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "qty",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
            [ "name" => "hpp",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
        ],
    ],

    ["name" => "ProjectManagement",
        "loging_date" => true,
        "loging_user" => true,
        "column" => [
            [ "name" => "id",
                "type" => "bigIncrements",
                "attributes" => ['index'],
            ],
            [ "name" => "code",
                "type" => "string",
            ],
            [ "name" => "name_of_vessel",
                "type" => "string",
            ],
            [ "name" => "lead_engineer",
                "type" => "string",
                "attributes" => ['nullable']
            ],
            [ "name" => "project_manager",
                "type" => "string",
                "attributes" => ['nullable']
            ],
            [ "name" => "start_date",
                "type" => "date",
            ],
            [ "name" => "end_date",
                "type" => "date",
            ],
        ],
    ],

    ["name" => "PaymentVouchers",
        "loging_date" => true,
        "loging_user" => true,
        "column" => [
            [ "name" => "id",
                "type" => "bigIncrements",
                "attributes" => ["index"],
            ],
            [ "name" => "code",
                "type" => "string",
                "attributes" => ["nullable"]
            ],
            [ "name" => "department_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "vendor_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "date",
                "type" => "date",
            ],
            [ "name" => "purchase_work_order_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"]
            ],
            [ "name" => "goods_work_receive",
                "type" => "unsignedBigInteger",
                "attributes" => ["index", "nullable"]
            ],
            [ "name" => "total",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
            [ "name" => "paid",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
            [ "name" => "remarks",
                "type" => "text",
                "attributes" => ["nullable"]
            ],
        ],
    ],

    ["name" => "JobCostings",
        "loging_date" => true,
        "loging_user" => true,
        "column" => [
            [ "name" => "id",
                "type" => "bigIncrements",
                "attributes" => ["index"],
            ],
            [ "name" => "code",
                "type" => "string",
                "attributes" => ["nullable"]
            ],
            [ "name" => "department_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "warehouse_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "date",
                "type" => "date",
            ],
            [ "name" => "is_approve",
                "type" => "tinyInteger",
                "default" => 0
            ],
            [ "name" => "approved_by",
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"]
            ],
            [ "name" => "approved_at",
                "type" => "date",
                "attributes" => ["nullable"]
            ],
            [ "name" => "remarks",
                "type" => "text",
                "attributes" => ["nullable"]
            ],
        ],
    ],
    ["name" => "JobCostingDetails",
        "loging_date" => true,
        "loging_user" => true,
        "column" => [
            [ "name" => "id",
                "type" => "bigIncrements",
                "attributes" => ["index"],
            ],
            [ "name" => "job_costing_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "item_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "qty",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ]
        ],
    ],
    
    ["name" => "InventoryAdjustments",
        "loging_date" => true,
        "loging_user" => true,
        "column" => [
            [ "name" => "id",
                "type" => "bigIncrements",
                "attributes" => ["index"],
            ],
            [ "name" => "code",
                "type" => "string",
                "attributes" => ["nullable"]
            ],
            [ "name" => "inventory_adjustments_date",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "warehouse_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "requested_by", // #1
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "approved_by", // #2
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],
            [ "name" => "rejected_by", // #2
                "type" => "unsignedBigInteger",
                "attributes" => ["nullable"],
            ],

            [ "name" => "note",
                "type" => "text",
                "attributes" => ["nullable"],
            ],
        ],
    ],

    ["name" => "InventoryAdjustmentItems",
        "loging_date" => true,
        "loging_user" => true,
        "column" => [
            [ "name" => "id",
                "type" => "bigIncrements",
                "attributes" => ["index"],
            ],
            [ "name" => "inventory_adjustmen_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "item_id",
                "type" => "unsignedBigInteger",
                "attributes" => ["index"],
            ],
            [ "name" => "stock",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
            [ "name" => "selling_price",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
            [ "name" => "cogs",
                "type"    => "double",
                "length"  => 18,
                "length2" => 2,
            ],
        ],
    ],
];  
